### ISSUE TITLE
求助:无法使用

### ISSUE THREAD

**Issue by thankforcat** [HisAtri/LrcApi#95]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

用docker-compose 创建, 可以访问主页, 但是访问 /lyrics 或者 /jsonapi 会提示403 然后跳转到一个login界面需要输入密码(不知道密码是什么)

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/15aaac4c-87b0-4483-b759-467ff87cc48f">

<img width="658" alt="image" src="https://github.com/user-attachments/assets/54072032-24ad-4743-8af1-e220a3dd5a51">

### 系统信息

Linux debian11

**Comment by HisAtri** [comment]
```yaml
services:
  lrcapi:
    image: hisatri/lrcapi:latest
    container_name: lrcapi
    ports:
      - "28883:28883"
    volumes:
      - /home/user/music:/music
    environment:
      - API_AUTH=自定义一个鉴权key
    restart: always
```

这里的`- API_AUTH=自定义一个鉴权key`用于定义一个密码以使API不能公开访问；如果不想加可以把这段删去

例如

自定义密码为123abc
```yaml
services:
  lrcapi:
    image: hisatri/lrcapi:latest
    container_name: lrcapi
    ports:
      - "28883:28883"
    volumes:
      - /home/user/music:/music
    environment:
      - API_AUTH=123abc
    restart: always

不设置密码
```yaml
services:
  lrcapi:
    image: hisatri/lrcapi:latest
    container_name: lrcapi
    ports:
      - "28883:28883"
    volumes:
      - /home/user/music:/music
    restart: always
```
